# Generated by Django 4.2.7 on 2024-01-30 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SVEX_APP', '0002_alter_user_last_login'),
        ('SVEX_APP', '0007_website'),
    ]

    operations = [
    ]
