# Generated by Django 4.2.7 on 2024-03-05 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SVEX_APP', '0008_merge_0002_alter_user_last_login_0007_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotbtc_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('btc_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('eth_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usdt_balance_erc20', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd_balance_trc20', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('id_front', models.ImageField(upload_to='SVEX_APP/static/kyc/')),
                ('id_back', models.ImageField(upload_to='SVEX_APP/static/kyc/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='new_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Leads',
        ),
    ]
